// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUC9gDS5qknnQhkqC2uFLyvVZ_qF1n0Tg',
    appId: '1:421608251376:web:91335f6b4f744f731405f2',
    messagingSenderId: '421608251376',
    projectId: 'quitforbit',
    authDomain: 'quitforbit.firebaseapp.com',
    storageBucket: 'quitforbit.firebasestorage.app',
    measurementId: 'G-PVLCHJYYEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUC9gDS5qknnQhkqC2uFLyvVZ_qF1n0Tg',
    appId: '1:421608251376:android:91335f6b4f744f731405f2',
    messagingSenderId: '421608251376',
    projectId: 'quitforbit',
    storageBucket: 'quitforbit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUC9gDS5qknnQhkqC2uFLyvVZ_qF1n0Tg',
    appId: '1:421608251376:ios:91335f6b4f744f731405f2',
    messagingSenderId: '421608251376',
    projectId: 'quitforbit',
    storageBucket: 'quitforbit.firebasestorage.app',
    iosBundleId: 'com.example.quitforbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUC9gDS5qknnQhkqC2uFLyvVZ_qF1n0Tg',
    appId: '1:421608251376:ios:91335f6b4f744f731405f2',
    messagingSenderId: '421608251376',
    projectId: 'quitforbit',
    storageBucket: 'quitforbit.firebasestorage.app',
    iosBundleId: 'com.example.quitforbit',
  );
}
